---
net_vlan_state: merged
net_vlan_config:
    - name: desktops
      vlan_id: 20
    - name: servers
      vlan_id: 30
    - name: printers
      vlan_id: 40
    - name: DMZ
      vlan_id: 50
    - name: DMZ-TEST
      vlan_id: 1050