---
- name: Gather arista eos facts
  arista.eos.eos_facts:
    gather_subset: config
#    gather_network_resources: "{{ network_resource | default('!bgp_global,!bgp_address_family') }}"
    gather_network_resources: all
