---
- name: Configure network VLANs
  hosts: arista
  gather_facts: false
  vars:
    - vlan_state: "{{ net_vlan_state | default('merged') }}"
    - vlan_config: "{{ net_vlan_config | default('') }}"
  tasks:
    - name: Assert that VLAN config was sent
      debug:
        msg: Configuring VLANS "{{ vlan_config }}"